### ISSUE TITLE
我有个问题

### ISSUE THREAD

**Issue by LateDreamXD** [WJZ-P/LiteLoaderQQNT-Change-Summary#1]
这个是只有自己能看到的对吧

**Comment by WJZ-P** [comment]
不是，所有人可见的

**Comment by LateDreamXD** [comment]
!! 感谢项目主还原了这个在QNotified/QAuxiliary中没用但有用的功能
Star献上

**Comment by WJZ-P** [comment]
> !! 感谢项目主还原了这个在QNotified/QAuxiliary中没用但有用的功能 Star献上

不客气，我自己也用QA
