### ISSUE TITLE
设置界面显示有点小问题呢

### ISSUE THREAD

**Issue by Starrain08** [WJZ-P/LiteLoaderQQNT-Change-Summary#5]
![image](https://github.com/user-attachments/assets/f5c0de1c-8c48-4e5d-8527-cd0706931c5b)
如题，(●'◡'●)

**Comment by WJZ-P** [comment]
已知问题。主要是由于插件界面HTML借鉴的防撤回插件导致的。已不适应新版QQ。后续会修复

**Comment by WJZ-P** [comment]
![a445912afc8320f2592885253fa5c081](https://github.com/user-attachments/assets/76964db5-71ac-45d3-906d-fcc105b57782)

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/0e0a552d-b7c6-459d-84e6-a3f31cc56953)
you'ge'qi'guai'de有个奇怪的点，我的QQ版本更新到了28131.为什么我的设置页面是正常的
请问你是Windows系统吗？

**Comment by WJZ-P** [comment]
你看我的这个设置页面，在夜晚模式下，右边的是更深色的

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/39095e2e-8e02-42c5-aa2c-29ee5ec01c53)
可能跟QQ的zhu'ti'she主题设置有关？我是用的这个主题

如果你需要的话还可以下个自定义背景插件，就能用自己的图片了，支持幻灯片放映什么的

**Comment by Starrain08** [comment]
> ![image](https://private-user-images.githubusercontent.com/110795301/378042024-0e0a552d-b7c6-459d-84e6-a3f31cc56953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDkwNDAsIm5iZiI6MTcyOTMwODc0MCwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MDQyMDI0LTBlMGE1NTJkLWI3YzYtNDU5ZC04NGU2LWEzZjMxY2M1Njk1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwMzMyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmEzNWQ2NDEyMmFlNzI3YTRhZDM0OGUxMWI5OWJlNzVhNDA1NTU5Y2E5ZGM4OWE2MTNjOTNlZWZiZGYxNTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xj8i_WOweClr7SvIwH4v2JeT2kVfDHY_821-dzxqpdM) you'ge'qi'guai'de有个奇怪的点，我的QQ版本更新到了28131.为什么我的设置页面是正常的 请问你是Windows系统吗？

我这里是Windows系统，但我版本较高

**Comment by Starrain08** [comment]
> 你看我的这个设置页面，在夜晚模式下，右边的是更深色的

额，怪欸，我这里一样也是深色模式

**Comment by LateDreamXD** [comment]
这个貌似是mspring的问题
![image](https://github.com/user-attachments/assets/7bce2b16-92ed-4608-afde-e4b10232348d)

先看看mspring那边修不修(当然我懒得去提issue (ˉ﹃ˉ)

**Comment by LateDreamXD** [comment]
#10 已修复
