### ISSUE TITLE
有点好奇是怎么实现的

### ISSUE THREAD

**Issue by biantwin** [WJZ-P/LiteLoaderQQNT-Change-Summary#6]
之前也经常看见这种表情包外显文本的，刚刚好看到这个项目，就想问一下这个大概是什么原理

**Comment by WJZ-P** [comment]
点个star就告诉你
![2b974419a7ba7d972f1e42bdd7ad0a57](https://github.com/user-attachments/assets/47edc25c-458f-4015-bb8b-2523b55683b3)

**Comment by WJZ-P** [comment]
哇，怎么没有回应
![cee65fa2dfb0facee17b1f06c99c9c4b](https://github.com/user-attachments/assets/f29dd472-ce76-41b5-ae3f-2d67b002af79)

**Comment by biantwin** [comment]
呱，没看到（），star是什么啊
![Uploading 1722181508769.jpg…]()

**Comment by biantwin** [comment]
呱，没看懂

**Comment by biantwin** [comment]
> 哇，怎么没有回应 ![cee65fa2dfb0facee17b1f06c99c9c4b](https://private-user-images.githubusercontent.com/110795301/378193816-f29dd472-ce76-41b5-ae3f-2d67b002af79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mzg2MjgsIm5iZiI6MTcyOTQzODMyOCwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MTkzODE2LWYyOWRkNDcyLWNlNzYtNDFiNS1hZTNmLTJkNjdiMDAyYWY3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNTMyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThhOTQ2ZjQzMmRmNDY3MmZjNTkwNmY0ZTJkNmQ0MGZkMTZkYThjNzMyNDFlNjBiZWE5Mzc3YTQ4MmIzMzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xAZ0SeqpnVFcIXMsZvWyBJlkZVNp58EAxS1PT39ji-M)

没看到（），star是什么啊
![1722181508769](https://github.com/user-attachments/assets/2d3ccf96-60b0-483c-a010-69829f554976)

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/2f0fdaf8-aeb6-4104-b164-3863979e8afe)
就这个，收藏

**Comment by biantwin** [comment]
> ![image](https://private-user-images.githubusercontent.com/110795301/378204154-2f0fdaf8-aeb6-4104-b164-3863979e8afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM4NzIsIm5iZiI6MTcyOTQ0MzU3MiwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MjA0MTU0LTJmMGZkYWY4LWFlYjYtNDEwNC1iMTY0LTM4NjM5NzllOGFmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNjU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNkMmNjZWViZmVkOTk4MDMwOWVhZmM2MzNlMjMyYTA1MzNlYjA5NzBkMzEyNzMwOTNjMmJkMGE0MGExZjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FpV81bq-kdNwF3iSZRg-D9maDEX57FwOR-5tsza1fhs) 就这个，收藏

好了喵
![Uploading 1722182089653.jpg…]()

**Comment by biantwin** [comment]
> ![image](https://private-user-images.githubusercontent.com/110795301/378204154-2f0fdaf8-aeb6-4104-b164-3863979e8afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDM5MTEsIm5iZiI6MTcyOTQ0MzYxMSwicGF0aCI6Ii8xMTA3OTUzMDEvMzc4MjA0MTU0LTJmMGZkYWY4LWFlYjYtNDEwNC1iMTY0LTM4NjM5NzllOGFmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjJjNzUwZmJjM2ZhZDJhYTZmMmI5ODM2Njc2MGQzN2U0OTc1MjQ4MmYxZThkMGVjOGQwMTA2YTc5NTY2M2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mQaBwXpEmHGnKFuG77T428OC9ks8vc9mAGifWWVVxFM) 就这个，收藏

![1722182089653](https://github.com/user-attachments/assets/e48e202c-3dd2-41c8-be08-ac0c7ebe7e5a) 好了喵

**Comment by WJZ-P** [comment]
好，其实实现原理就是通过修改发送图片时的summary属性。在发图片或者表情包的时候，发送的元素里面有summary这个属性，改成自己想要的就行了

**Comment by biantwin** [comment]
> 好，其实实现原理就是通过修改发送图片时的summary属性。在发图片或者表情包的时候，发送的元素里面有summary这个属性，改成自己想要的就行了

懂了，手机有办法实现吗

**Comment by WJZ-P** [comment]
> > 好，其实实现原理就是通过修改发送图片时的summary属性。在发图片或者表情包的时候，发送的元素里面有summary这个属性，改成自己想要的就行了
> 
> 懂了，手机有办法实现吗

有啊，手机QQ降点版本，装个太极，然后装QA模块，里面就有这个功能。但是手机模块我并不是很了解代码
