### ISSUE TITLE
[BUG]: 发送表情失败，并导致界面消失

### ISSUE THREAD

**Issue by WoodenP1ckaxe** [WJZ-P/LiteLoaderQQNT-Change-Summary#7]
无法发送表情
试图发送表情后 表情界面会变为空白
并且关闭并重新打开聊天窗口会导致整个聊天界面空白
![image](https://github.com/user-attachments/assets/425aef6d-8453-453b-816e-190204984e69)

该BUG貌似只影响表情
发送图片可以正常运作

LiteLoader版本1.2.2
QQNT版本9.9.15-26909
其他插件关闭情况下测试结果相同

**Comment by WJZ-P** [comment]
![image](https://github.com/user-attachments/assets/21ee4925-f9c2-4765-9445-1d4c60a75377)
我尝试了发送这里面的两种，均无异常，无法复现你的情况。你是打开的独立聊天窗口吧，我也开了测试，但是没发现有异常
![b3ce8982edccf482282600639589ab19](https://github.com/user-attachments/assets/05749a31-c688-4bbb-93d8-74c36077fe95)

**Comment by WJZ-P** [comment]
插件在渲染端完全没有做过修改，不知道为什么会出现你的情况

**Comment by WJZ-P** [comment]
@echo off
chcp 65001
TITLE NTQQ
"E:\NTQQ\QQ.exe" --enable-logging

如果可以的话，请你创建一个.bat为后缀的文件，文件名无所谓，然后以记事本方式打开，写入上面的内容，注意QQ路径要换成你自己的，然后双击它就会打开QQ，请你看看在bug出现的时候控制台有什么报错信息，这样可以帮助我判断是哪里出了问题

**Comment by WJZ-P** [comment]
hello?还在吗

**Comment by LateDreamXD** [comment]
路过(

**Comment by WoodenP1ckaxe** [comment]
> @echo off chcp 65001 TITLE NTQQ "E:\NTQQ\QQ.exe" --enable-logging
> 
> 如果可以的话，请你创建一个.bat为后缀的文件，文件名无所谓，然后以记事本方式打开，写入上面的内容，注意QQ路径要换成你自己的，然后双击它就会打开QQ，请你看看在bug出现的时候控制台有什么报错信息，这样可以帮助我判断是哪里出了问题

刚看到消息 我的电脑重启了之后 这个BUG就没法复现了

**Comment by WJZ-P** [comment]
那就不知道了，可能是偶然的bug

**Comment by WJZ-P** [comment]
能复现的时候再reopen吧
