### ISSUE TITLE
设置无法永久保存

### ISSUE THREAD

**Issue by mcwuguodadi** [WJZ-P/LiteLoaderQQNT-Change-Summary#9]
# 问题描述
如题，当QQ重启后会丢失全部的配置

# 一些信息
插件版本 1.1.2
LiteLoader 1.2.2
NTQQ 9.9.15-27597

**Comment by WJZ-P** [comment]
```{
        const config = await csAPI.getConfig()
        isPicOTuseRandom = config.isPicOTuseRandom;
        isMemeOTuseRandom = config.isMemeOTuseRandom;

        const picInputEl = this.document.querySelector('#cs-input-pic')
        const memeInputEl = this.document.querySelector('#cs-input-meme')
        picInputEl.value = config.picOutsideText
        memeInputEl.value = config.memeOutsideText
```

上面是设置页面的代码。如果QQ重启后没有保存配置的话，请看看插件目录下是否有config.json这个文件呢？或者说你的插件目录是在C盘吗？不知道会不会存在权限之类的问题

**Comment by mcwuguodadi** [comment]
> ```
>         const config = await csAPI.getConfig()
>         isPicOTuseRandom = config.isPicOTuseRandom;
>         isMemeOTuseRandom = config.isMemeOTuseRandom;
> 
>         const picInputEl = this.document.querySelector('#cs-input-pic')
>         const memeInputEl = this.document.querySelector('#cs-input-meme')
>         picInputEl.value = config.picOutsideText
>         memeInputEl.value = config.memeOutsideText
> ```
> 
> 上面是设置页面的代码。如果QQ重启后没有保存配置的话，请看看插件目录下是否有config.json这个文件呢？或者说你的插件目录是在C盘吗？不知道会不会存在权限之类的问题

左侧是LiteLoader本体目录的位置下插件的config.json文件，右侧是数据目录位置下插件的config.json文件
改动插件配置后改动的是LiteLoader本体目录的位置下插件的config.json（如图）

有没有可能是QQ启动后加载的是数据目录位置下插件的config.json？
![image](https://github.com/user-attachments/assets/84978ff4-089d-4c11-ba26-722161f2ab1d)

**Comment by WJZ-P** [comment]
诶？这个地方居然有两份吗，我做的所有插件都是改和读取左侧的本体目录下插件的config才对，没有改过这个右侧在QQNT里面的。
![image](https://github.com/user-attachments/assets/b9c9a79a-b1f9-4d32-a791-04388aa3208a)

插件应该放在数据目录位置内就没问题了。推荐所有插件都放这个里面，你可以下个插件列表查看插件，里面默认装插件都是数据目录。

我自己的本体目录内没有plugins文件夹，建议你把本体目录下的插件移动到数据目录内看看

**Comment by mcwuguodadi** [comment]
QQ启动→读取应用D盘下的config文件→用户修改写入的是C盘下的config文件，重启后之前的变动就无效了
应该是这个逻辑.gif

**Comment by WJZ-P** [comment]
怎么有两份config.json，我的本体目录是这样的：
![image](https://github.com/user-attachments/assets/df869034-a25a-44ef-8c10-76f239afa76b)
没有pluginsw文件夹。把C盘那个plugins文件夹移植到D盘里头看看

**Comment by mcwuguodadi** [comment]
把C盘下的插件删了之后两个地方的配置文件都没被修改
把数据目录下的插件删除了等于把插件卸载了
![image](https://github.com/user-attachments/assets/b90609c1-19bf-4d0f-8cfd-b1ebe95ab7e9)


我尝试一下重装插件

**Comment by WJZ-P** [comment]
有点奇葩，从来没有遇见过这个情况，真神奇
![ec91727f7dfaabaf9a491f3a557a4757](https://github.com/user-attachments/assets/8074290c-42c9-4ffc-9a15-2db407a7e041)

**Comment by mcwuguodadi** [comment]
把C盘下面的plugins文件夹整个删了然后重装插件修复了
```
"pluginPath": "D:\\documents\\LiteloaderQQNT\\plugins\\change_summary",
"configPath": "D:\\documents\\LiteloaderQQNT\\plugins\\change_summary\\config.json"
````
或许和配置文件中的这两个路径有关？真神奇.jpg

**Comment by WJZ-P** [comment]
这个是第一次启动插件的时候，根据LL本体的数据目录自动生成的。可能你后面更改了数据目录？但是插件里面初始化时候的是旧的

**Comment by WJZ-P** [comment]
是删除重装先生，我的插件有救了！
![c9dc18a15dc8a0f9a63e0fda6c46a80a](https://github.com/user-attachments/assets/97279f88-49b5-4caf-b0f2-7623c0a80d24)

**Comment by mcwuguodadi** [comment]
![image](https://github.com/user-attachments/assets/b781c948-4d2f-4b5e-bb9f-069004d7322c)
使用的config文件不在插件目录下会出现这个问题（

启动后加载的是插件列表下的config，修改设置是修改"configPath"的config文件，然而启动加载的不是"configPath"的config文件，所以设置的数据都丢失了

这应该算是个bug吧？但是重装就能解决（

**Comment by WJZ-P** [comment]
```
const pluginPath = path.join(LiteLoader.plugins.change_summary.path.plugin);//插件目录
const configPath = path.join(pluginPath, "config.json");
```
这是main.js的代码。可以看到configPath是在pluginPath的基础上生成的。所以理论上不应该出现像你图中这样的情况，有可能是LL本身的bug。毕竟我代码这个路径生成就是上面那两行，不应该有问题才对

**Comment by mcwuguodadi** [comment]
> ```
> const pluginPath = path.join(LiteLoader.plugins.change_summary.path.plugin);//插件目录
> const configPath = path.join(pluginPath, "config.json");
> ```
> 
> 这是main.js的代码。可以看到configPath是在pluginPath的基础上生成的。所以理论上不应该出现像你图中这样的情况，有可能是LL本身的bug。毕竟我代码这个路径生成就是上面那两行，不应该有问题才对

刚开始确实是我安装的方式不正确导致的，是我的锅：D（之前安装liteloader的时候好像报了个插件列表安装失败什么的，就手动安装了这个插件）

不过现在没事了，不随意动config的文件路径就行了

**Comment by mcwuguodadi** [comment]
issue我先关了，注意休息哦~

**Comment by WJZ-P** [comment]
好，装个插件列表查看挺方便的，就是插件商店的功能，能直接在QQ安装插件。我还做了一些别的插件，欢迎使用
![4629c463221ecc3cfadd8d14021164f7](https://github.com/user-attachments/assets/61286264-78e9-41c9-9847-0a502b25ec75)

**Comment by mcwuguodadi** [comment]
> 好，装个插件列表查看挺方便的，就是插件商店的功能，能直接在QQ安装插件。我还做了一些别的插件，欢迎使用 ![4629c463221ecc3cfadd8d14021164f7](https://private-user-images.githubusercontent.com/110795301/384453341-61286264-78e9-41c9-9847-0a502b25ec75.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQ3MTAsIm5iZiI6MTczMTA4NDQxMCwicGF0aCI6Ii8xMTA3OTUzMDEvMzg0NDUzMzQxLTYxMjg2MjY0LTc4ZTktNDFjOS05ODQ3LTBhNTAyYjI1ZWM3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNjQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTBlYTNkMWYwNWNlOWRhNmYwMzdhNzViYjQ0MjI3YjAxMzIzZGE2MzdmNTdiNWNjNWQ0MWM1ZDdmOTRmMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GtxjB-XI6Ort4HmUpuvAtuQ8sodBj30QTsOhIIdvbj0)

现在已经用上了，真方便（

**Comment by LateDreamXD** [comment]
awa
